In [2]:
from numpy import random
x = random.randint(100)
print(x)


47


In [4]:
y= random.rand()
print(y)

0.13363309623692776


In [7]:
## Generating random array
x = random.randint(100, size=(5))# 1d array
print(x)
y= random.randint(100, size=(3, 4)) # 2d array
print(y)

[39 43 50 33 58]
[[64 29 62 47]
 [13 62 30 32]
 [20 50  9 65]]


* choice() method allow you to generate a random value based on array of values
* choice() method takes an array as a parameter and randomly returns one of the values

In [8]:
x = random.choice([3, 5, 7, 9])
print(x)

9


In [9]:
x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[7 5 3 9 5]
 [9 3 7 5 9]
 [7 9 9 3 7]]


### Data distribution
* Data distribution is a list of all possible values, and how oftern each value occurs.
* Such list are important when working with statistics and data science.

### Random distribution
* Random distribution is a set of random numbers taht follow a certain distribution density function.
* Probability Density Function: A function that describes a continuous probability. i.e. probability of all values in an array.
We can generate random numbers based on defined probabilities using the choice() method of the random module.

The choice() method allows us to specify the probability for each value.

The probability is set by a number between 0 and 1, where 0 means that the value will never occur and 1 means that the value will always occur.

In [10]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.4, 0.2], size=(3,4)) # probabability for val to be 3 is set to 0.1 and so on
print(x)

[[7 7 5 5]
 [9 9 7 7]
 [9 7 7 9]]


In [ ]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))
print(x)x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))


[7 7 7 7 5 5 7 5 5 5 7 5 7 7 5 5 5 5 5 7 7 7 7 7 7 5 3 5 7 7 3 5 7 7 7 5 7
 7 7 3 5 7 7 3 7 7 7 3 7 3 5 7 7 7 5 7 5 7 5 7 3 3 7 7 5 7 5 7 3 7 7 5 7 7
 7 5 7 7 5 5 7 5 7 5 7 7 7 7 5 5 5 5 7 5 5 7 7 5 7 7]


In [12]:
## shuffling array
## changing arrangement of array
from numpy import random
import numpy as np
 
arr = np.array([1, 2, 3, 4, 5])
random.shuffle(arr)
print(arr)

[3 2 1 5 4]


In [14]:
# generating permutation of array
arr = np.array([1, 2, 3, 4, 5])
print(random.permutation(arr))# original array is not changed


[5 1 4 3 2]
